[package]
name = "dh-devices"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
detguest-host.workspace = true
detguest-wire.workspace = true
dh-inputlog.workspace = true
rand_chacha = { version = "0.3", default-features = false }
rand_core = { version = "0.6", default-features = false }
