[package]
name = "dh-vmm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dh-detclock.workspace = true
dh-devices.workspace = true
dh-inputlog.workspace = true
dh-proto.workspace = true
dh-snapshot.workspace = true
blake3.workspace = true
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
libc = "0.2.186"
vm-memory = { version = "0.18.0", features = ["backend-mmap"] }
vmm-sys-util = "0.15.0"

[dev-dependencies]
nanokernel = { path = "../../tests/nanokernel" }
